name: Generate terraform docs
on:
  pull_request:
    paths:
      - */**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          output-fmodulesile: README.md
          output-method: inject
          git-push: "true"